config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'search', to: 'application#search'
  resources :books, only: [:index, :show] 
  resources :library_branches, only: [:show]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :library_branch
  has_many :borrowings
  has_many :users, through: :borrowings
  has_many :reviews

  #Validations
  validates :title, presence: true
  validates :author, presence: true

  def self.search(query)
    where('LOWER(title) LIKE LOWER(:query) OR LOWER(author) LIKE LOWER(:query) OR LOWER(genre) LIKE LOWER(:query)', query: "%#{query.downcase}%")
  end
end  

app/models/borrowing.rb
class Borrowing < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/library_branch.rb
class LibraryBranch < ApplicationRecord
  has_many :books

  # Assuming 'location' holds the address for geocoding
  geocoded_by :location
  # Ensure that geocode is called only if location is present and has changed
  after_validation :geocode, if: ->(obj){ obj.location.present? && obj.location_changed? }

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
    has_many :borrowings
    has_many :books, through: :borrowings
    has_many :reviews

    #Validations
    validates :name, presence: true
    validates :email, presence: true, uniqueness: { case_sensitive: false }
end

app/models/weather.rb
class Weather < ApplicationRecord
    
    #Validations
    validates :location, presence: true
    validates :temperature, presence: true
    validates :humidity, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
    validates :wind_speed, numericality: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def search
        @books = Book.where('title LIKE ?', "%#{params[:query]}%")
        render 'books/index'
      end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

def show
  @book = Book.includes(:library_branch, :reviews).find(params[:id])
end

def index
  if params[:search].present?
    @books = Book.where('title LIKE ?', "%#{params[:search]}%")
  else
    @books = Book.all
  end
  @books = Book.page(params[:page]).per(10) 
  end
end

app/controllers/library_branches_controller.rb
class LibraryBranchesController < ApplicationController
    def show
      @library_branch = LibraryBranch.find(params[:id])
    end
  end
  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/index.html.erb
<% if @books.present? %>
  <% @books.each do |book| %>
  <% end %>
<% else %>
  <p>No results found.</p>
<% end %>

<h1>Books Collection</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p>Author: <%= @book.author %></p>
<p>Genre: <%= @book.genre %></p>
<p>Library Branch: <%= link_to @book.library_branch.name, library_branch_path(@book.library_branch) %></p>

<!-- Display associated reviews -->
<h3>Reviews</h3>
<ul>
  <% @book.reviews.each do |review| %>
    <li><%= review.content %> - <%= review.user.name %></li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<p>Books in this category:</p>
<ul>
  <% @category.books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntroToRails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
  <%= javascript_importmap_tags %>

  <!-- Add Mapbox CSS -->
  <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />

  <!-- Add Mapbox JS -->
  <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
  

</head>

<body>
  <nav>
    <%= link_to 'Home', root_path %> |
    <%= link_to 'About', about_path %> |
    <%= link_to 'Books', books_path %>
  </nav>
  <%= render 'shared/search_form' %>
  <%= yield %>
</body>
</html>

app/views/library_branches/show.html.erb
<h1><%= @library_branch.name %></h1>
<p>Location: <%= @library_branch.location %></p>

<div id='map' style='width: 600px; height: 300px;'></div>

<script>
  mapboxgl.accessToken = 'pk.eyJ1IjoiZm9udGVsYXJjaiIsImEiOiJjbHRya3UxZ3owN3puMnJwaW9zczNuYnZyIn0.lVEyzieDPflukT_oP2FzeA'; 
  var map = new mapboxgl.Map({
    container: 'map', // The container ID
    style: 'mapbox://styles/mapbox/streets-v11', // The map style to use
    center: [-98.5795, 39.8283], // Starting position [lng, lat] - Center of the USA
    zoom: 3 // Starting zoom level
  });

  new mapboxgl.Marker()
    .setLngLat([<%= @library_branch.longitude %>, <%= @library_branch.latitude %>])
    .addTo(map);
</script>

app/views/shared/_search_form.html.erb
<%= form_with(url: search_path, method: :get, local: true) do |form| %>
    <%= form.search_field :query, placeholder: 'Search books...', aria_label: 'Search books' %>
    <%= form.submit 'Search' %>
  <% end %>

app/views/static_pages/about.html.erb
<h1>About This Application</h1>
<p>This application utilizes data from several sources to provide users with comprehensive information about...</p>

<h2>Data Sources</h2>
<ul>
  <li>OpenWeatherMap API for real-time weather data.</li>
  <li>Faker for generating dynamic user data.</li>
  <li>Custom CSV file for library data including Books and their Title, Author, Genre, Publication Year, Library Name and Library Branch.</li>
</ul>

<h3>Entity Relationship Diagram for Database</h3>

<%# Optionally include an ERD image if you have one %>
<%= image_tag('ERD.png', alt: 'Entity Relationship Diagram') %> 

app/views/static_pages/home.html.erb
<h1>Welcome to my Library!</h1>

<% if Book.any? %>
  <p>We have <%= Book.count %> amazing books for you to explore. Check out our collection!</p>
  <% random_book = Book.order("RANDOM()").first %>
  <p>Why not start with a recommendation? Take a look at "<%= random_book.title %>" by <%= random_book.author %>.</p>
<% else %>
  <p>This is the home page. Our collection is currently empty, but we will have a great selection of books for you soon!</p>
<% end %>